CC=gcc
CFLAGS=-std=gnu99

all:
	$(CC) $(CFLAGS) ./task1/write.c -o ./task1/write.out
	$(CC) $(CFLAGS) ./task1/read.c -o ./task1/read.out


clean:
	find . -name \*.o -type f -delete

delete:
	find . -name \*.out -type f -delete
