CC=gcc
CFLAGS=-std=gnu99

all:
	$(CC) $(CFLAGS) ./task1/main.c -o ./task1/main 
	$(CC) $(CFLAGS) ./task2/main.c -o ./task2/main
	$(CC) $(CFLAGS) ./task3/main.c -o ./task3/main
	$(CC) $(CFLAGS) ./task4/main.c -o ./task4/main

clean:
	rm -rf *.o main
