CC=gcc
CFLAGS=-std=gnu99

all:
	$(CC) $(CFLAGS) ./task1.c -o ./task1.out
	$(CC) $(CFLAGS) ./task2.c -o ./task2.out
	$(CC) $(CFLAGS) ./1.c -o ./1.out
	$(CC) $(CFLAGS) ./2.c -o ./2.out

clean:
	find . -name \*.o -type f -delete

delete:
	find . -name \*.out -type f -delete
